version: '3'

services:
  reverse-proxy:
    container_name: traefik
    image: traefik:v3.2
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.web-secure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=rraines@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme.json"
      - "--log.level=DEBUG"
      - "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
      - "--accesslog=true"
      - "--accesslog.filepath=/var/log/traefik/access.log"
    network_mode: "host"
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - opt/docker//traefik/acme.json:/etc/traefik/acme.json
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log/traefik:/var/log/traefik
    labels:
      - "traefik.enable=true"

networks:
  traefik-servicenet:
    external: true
    name: traefik-servicenet