version: '3.8'
services:
  channels-dvr:
    image: fancybits/channels-dvr:tve
    container_name: channels-dvr
    network_mode: host
    ports:
      - "8089:8089"
    restart: on-failure:10
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /opt/channels-dvr:/channels-dvr
      - /mnt/dvr/:/mnt/dvr